server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: sailing-game-backend
  
  datasource:
    url: jdbc:h2:mem:sailing_game
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

logging:
  level:
    com.adventure: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG

# Game configuration
game:
  initial-gold: 100
  initial-health: 100
  max-health: 100
  story-delay: 2000 